# General config
max_redirects = 2
timeout = 4000       # milliseconds
resolve_media = true

# prefixes to strip from domains before testing
prefixes = ["www.", "www2."]

# patterns starting with % should match the `sites` table
# otherwise this will be a list of regexes for domain names
#
# It's good practice to terminate patterns with $ to avoid fake subdomains like "youtube.com.myscamwebsite.net"
allow_html = [
    '''lantern\.chat$''', # We don't actually have any HTML embeds, and may never, but still a good default.
    "%youtube",
    # "%twitter", # unknown if twitter embeds anything meaningful
    "%reddit",
    "%spotify",
    "%twitch",
    "%soundcloud",
    "%pornhub",
    "%dailymotion",
    '''vimeo\.com$''',
    '''rdio\.com$''',
    '''slideshare\.net$''',
    '''yewtu\.be$''',
    '''bandcamp\.com$''',
    '''lightspeed\.tv$''',
]

skip_oembed = [
    '''fxtwitter\.com$''', # gives more generic information than the meta tags, so should be avoided
]

# The % prefix is just convention at this point, these are just string literal keys
[user_agents]
"%browser" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0"
"%discord" = "Mozilla/5.0 (compatible; Discordbot/2.0; +https://discordapp.com)"
"%test" = "test"

# https://www.netify.ai/resources/applications/youtube
[sites.youtube]
color = 0xFF0000
# https://www.javainuse.com/rexgenerator + manual tweaking
pattern = '''youtube(?:\.com?)?(?:\.(?:c(?:at|[hlorz])|s(?:oy|[aegiknv])|ca|a[elmrtuz]|b[adeghory]|d[eko]|e[cegs]|f[ir]|g[ehrt]|h[knru]|i[delnqst]|j[mop]|k[erwz]|l[abkt-vy]|m[adekntxy]|n[giloz]|om|p[aehklrty]|qa|r[osu]|t[hnrvwz]|u[agky]|v[en]|z[aw]))?$'''
# Domains are ADDITIVE to the pattern, checked before regex evaluation
domains = [
    "googlevideo.com",
    "gvt1.com",
    "video.google.com",
    "video.l.google.com",
    "youtu.be",
    "youtube.com",
    "music.youtube.com",
    "youtube-nocookie.com",
    "youtube-ui.l.google.com",
    "youtube.googleapis.com",
    "youtubeeducation.com",
    "youtubeembeddedplayer.googleapis.com",
    "youtubei.googleapis.com",
    "youtubekids.com",
    "yt-video-upload.l.google.com",
    "yt.be",
    "yt3.ggpht.com",
    "ytimg.com",
    "ytimg.l.google.com",
    "ytkids.app.goo.gl",
]

# https://www.netify.ai/resources/applications/twitter
[sites.twitter]
color = 0x1DA1F2
pattern = '''\.twitter\.com$'''
domains = [
    "t.co",
    "tweetdeck.com",
    "twimg.com",
    "twitpic.com",
    "twitter.co",
    "twitter.com",
    "twitterinc.com",
    "twitteroauth.com",
    "twitterstat.us",
    "twttr.com",
]

# https://www.netify.ai/resources/applications/reddit
# https://securitytrails.com/list/apex_domain/www.reddit.com
[sites.reddit]
color = 0xFF4500
pattern = '''reddit\.com$'''
domains = [
    "redd.it",
    "reddit.com",
    "redditblog.com",
    "redditinc.com",
    "redditmail.com",
    "redditmedia.com",
    "redditstatic.com",
    "redditstatus.com",
]

# https://www.netify.ai/resources/applications/discord
# https://subdomainfinder.c99.nl/scans/2020-05-03/discord.com
[sites.discord]
color = 0x5865F2
domains = [
    "discord.com",
    "discord.gg",
    "discord.media",
    "discordapp.com",
    "discordapp.net",
    "cdn.discordapp.com",
    "cdn.discordapp.net",
    "discordstatus.com",
    "canary.discord.com",
    "ptb.discord.com",
    "blog.discord.com",
    "printer.discord.com",
    "safety.discord.com",
    "status.discord.com",
]

[sites.giphy]
color = 0x9933FF
pattern = '''giphy\.com$'''

[sites.spotify]
color = 0x1DB954
pattern = '''(?:play|open)\.spotify\.com$'''

[sites.twitch]
color = 0x9146FF
pattern = '''twitch\.tv$'''

[sites.dailymotion]
color = 0x00AAFF
pattern = '''dailymotion\.com$'''

[sites.slashdot]
color = 0x006666
pattern = '''slashdot\.org$'''

[sites.soundcloud]
color = 0xF26F23
pattern = '''soundcloud\.com$'''

[sites.pornhub]
color = 0xFFA31A
pattern = '''pornhub\.com$'''

[sites.wikipedia]
color = 0xFFFFFF
pattern = '''(?:wik(?:i(?:versity|(?:(?:sourc|quot)e|voyage|(?:book|new)s|[mp]edia))|tionary)|mediawiki)\.org$'''

[sites.google]
color = 0x4285f4
pattern = '''google\.com$'''

[sites.hackernews]
color = 0xff4000
domains = ["news.ycombinator.com"]

[sites.linkedin]
color = 0x0077b5
pattern = '''linkedin\.com$'''
user_agent = "%browser"

# https://pages.ebay.com/securitycenter/security_researchers_eligible_domains.html
[sites.ebay]
color = 0xe53238
pattern = '''ebay\.(?:co(:?\.(:?jp|th))?|com(:?\.(?:au|hk|sg|my))?|de|ca|fr|it|es|at|ch|in|ph|ie|pl|be|nl|cn)$'''
domains = [
    "ebay.com",
    "ebaynyc.com",
    "shopping.com",
    "nexpartstaging.com",
    "whisolutions.com",
    "shutl.com",
    "about.co.kr",
    "ebaycommercenetwork.com",
    "ebayinc.com",
    "knownorigin.io",
    "portal.knownorigin.io",
    "tcgplayer.com",
    "rocarobotics.com",
    "binderpos.com",
    "channelfireball.com",
]

[sites.apple]
color = 0x000000
pattern = '''apple\.com$'''
domains = [
    "aaplimg.com",
    "apple",
    "apple-dns.cn",
    "apple-dns.net",
    "apple-mapkit.com",
    "apple.co",
    "apple.com",
    "apple.com.cn",
    "apple.news",
    "cdn-apple.com",
    "mzstatic.com",
]

[sites.tumblr]
color = 0x35465c
pattern = '''tumblr\.com$'''

# https://github.com/dylanpdx/BetterTwitFix/blob/7a1c00ebdb6479afbfcca6d84450039d29029a75/twitfix.py#L35
[sites.vxtwitter]
domains = ["vxtwitter.com", "d.vx"]
user_agent = "%test"

[sites.fxfuraffinity]
domains = ["fxfuraffinity.net"]
user_agent = "%discord"

# TODO: https://github.com/reimertz/brand-colors/blob/master/data/brandColors.json
